from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def safe_str(value, default="N/A"):
    if value is None or value == "":
        return default
    return str(value)


def get_value(data: dict, keys: list[str], default="N/A"):
    if not data:
        return default
    for key in keys:
        if key in data and data[key] is not None and data[key] != "":
            return data[key]
    return default


def build_pdf_report(data: dict) -> BytesIO:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    heading_style = styles["Heading2"]
    normal_style = styles["BodyText"]

    small_style = ParagraphStyle(
        "SmallStyle",
        parent=normal_style,
        fontSize=10,
        leading=14,
    )

    elements = []

    elements.append(Paragraph("NeuroBehavior AI - Behavioral Screening Report", title_style))
    elements.append(Spacer(1, 0.2 * inch))

    disclaimer = (
        "This report is a behavioral screening support summary generated by NeuroBehavior AI. "
        "It is not a medical or clinical diagnosis."
    )
    elements.append(Paragraph(disclaimer, small_style))
    elements.append(Spacer(1, 0.25 * inch))

    # Overall Summary
    final_result = data.get("final_result", {}) or {}
    elements.append(Paragraph("Overall Summary", heading_style))
    elements.append(Spacer(1, 0.1 * inch))

    summary_table_data = [
        ["Overall Score", safe_str(get_value(final_result, ["overall_score", "overallScore"]))],
        ["Overall Risk", safe_str(get_value(final_result, ["overall_risk", "overallRisk"]))],
        [
            "Dominant Concern Area",
            safe_str(get_value(final_result, ["dominant_concern_area", "dominantConcernArea"])),
        ],
        ["Available Modules", safe_str(get_value(final_result, ["available_modules", "availableModules"]))],
    ]

    summary_table = Table(summary_table_data, colWidths=[200, 280])
    summary_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(summary_table)
    elements.append(Spacer(1, 0.2 * inch))

    final_summary = safe_str(get_value(final_result, ["final_summary", "finalSummary"]))
    recommendation = safe_str(get_value(final_result, ["recommendation"]))

    elements.append(Paragraph(f"<b>Final Summary:</b> {final_summary}", small_style))
    elements.append(Spacer(1, 0.1 * inch))
    elements.append(Paragraph(f"<b>Recommendation:</b> {recommendation}", small_style))
    elements.append(Spacer(1, 0.25 * inch))

    # Typing Analysis
    typing_result = data.get("typing_result", {}) or {}
    elements.append(Paragraph("Typing Analysis", heading_style))
    elements.append(Spacer(1, 0.1 * inch))

    typing_table_data = [
        ["WPM", safe_str(get_value(typing_result, ["wpm"]))],
        ["Accuracy", safe_str(get_value(typing_result, ["accuracy"]))],
        ["Errors", safe_str(get_value(typing_result, ["errors"]))],
        ["Risk Level", safe_str(get_value(typing_result, ["risk_level", "riskLevel"]))],
        ["Summary", safe_str(get_value(typing_result, ["summary_text", "summaryText"]))],
    ]

    typing_table = Table(typing_table_data, colWidths=[200, 280])
    typing_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(typing_table)
    elements.append(Spacer(1, 0.25 * inch))

    # Attention Analysis
    attention_result = data.get("attention_result", {}) or {}
    elements.append(Paragraph("Attention Analysis", heading_style))
    elements.append(Spacer(1, 0.1 * inch))

    attention_table_data = [
        [
            "Attention Score",
            safe_str(get_value(attention_result, ["attention_score", "attentionScore", "score"])),
        ],
        ["Focus Level", safe_str(get_value(attention_result, ["focus_level", "focusLevel"]))],
        [
            "Impulsivity Level",
            safe_str(get_value(attention_result, ["impulsivity_level", "impulsivityLevel"])),
        ],
        ["Risk Level", safe_str(get_value(attention_result, ["risk_level", "riskLevel"]))],
        [
            "Summary",
            safe_str(
                get_value(
                    attention_result,
                    ["summary_text", "summaryText", "behavior_summary", "behaviorSummary"],
                )
            ),
        ],
    ]

    attention_table = Table(attention_table_data, colWidths=[200, 280])
    attention_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(attention_table)
    elements.append(Spacer(1, 0.25 * inch))

    # Reading Analysis
    reading_result = data.get("reading_result", {}) or {}
    elements.append(Paragraph("Reading Analysis", heading_style))
    elements.append(Spacer(1, 0.1 * inch))

    reading_table_data = [
        ["Reading Speed", safe_str(get_value(reading_result, ["reading_speed", "readingSpeed", "wpm"]))],
        [
            "Comprehension Score",
            safe_str(get_value(reading_result, ["comprehension_score", "comprehensionScore"])),
        ],
        ["Correct Answers", safe_str(get_value(reading_result, ["correct_answers", "correctAnswers"]))],
        ["Reading Risk", safe_str(get_value(reading_result, ["reading_risk", "readingRisk", "risk_level", "riskLevel"]))],
        ["Summary", safe_str(get_value(reading_result, ["summary_text", "summaryText"]))],
    ]

    reading_table = Table(reading_table_data, colWidths=[200, 280])
    reading_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("PADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    elements.append(reading_table)
    elements.append(Spacer(1, 0.25 * inch))

    # ML Prediction
    prediction_result = data.get("prediction_result", {}) or {}
    if prediction_result:
        elements.append(Paragraph("ML Prediction", heading_style))
        elements.append(Spacer(1, 0.1 * inch))

        probs = prediction_result.get("probabilities", {}) or {}

        low_prob = probs.get("Low", probs.get("low", "N/A"))
        medium_prob = probs.get("Medium", probs.get("medium", "N/A"))
        high_prob = probs.get("High", probs.get("high", "N/A"))

        prediction_table_data = [
            [
                "Predicted Risk",
                safe_str(get_value(prediction_result, ["predicted_risk", "predictedRisk"])),
            ],
            ["Confidence", safe_str(get_value(prediction_result, ["confidence"]))],
            ["Low Probability", safe_str(low_prob)],
            ["Medium Probability", safe_str(medium_prob)],
            ["High Probability", safe_str(high_prob)],
            ["Summary", safe_str(get_value(prediction_result, ["summary_text", "summaryText"]))],
        ]

        prediction_table = Table(prediction_table_data, colWidths=[200, 280])
        prediction_table.setStyle(
            TableStyle(
                [
                    ("BOX", (0, 0), (-1, -1), 1, colors.black),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("PADDING", (0, 0), (-1, -1), 8),
                ]
            )
        )
        elements.append(prediction_table)
        elements.append(Spacer(1, 0.25 * inch))

    doc.build(elements)
    buffer.seek(0)
    return buffer